config/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("usuario/", include("usuario.urls")),
    path("paciente/", include("paciente.urls")),
    path('turnos/', include('turnos.urls')),
]

core/urls.py
from django.contrib.auth.views import LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from . import views

app_name = "core"


urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(template_name="core/logout.html"), name="logout"),
    path("register/", views.register, name="register"),
    path("about/", views.about, name="about"),
    path("paciente/", views.paciente, name="paciente"),
    path("turnos/", views.turnos, name="turnos"),
    
]

urlpatterns += staticfiles_urlpatterns()

paciente/urls.py
from django.urls import path
from . import views

app_name = "paciente"

urlpatterns = [
    path("", views.home, name="home"),
    path("editar_paciente/", views.editar_paciente, name="editar_paciente"),
    path("paciente/list/", views.PacienteListView.as_view(), name="paciente_list"),
    path("paciente/create/", views.PacienteCreateView.as_view(), name="paciente_create"),
    path("paciente/detail/<int:pk>", views.PacienteDetailView.as_view(), name="paciente_detail"),
    path("paciente/update/<int:pk>", views.PacienteUpdateView.as_view(), name="paciente_update"),
    path("paciente/delete/<int:pk>", views.PacienteDeleteView.as_view(), name="paciente_delete"),
]

paciente/models.py
from django.db import models
from django.utils import timezone
from datetime import date

class Paciente(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    email = models.EmailField(max_length=254, null=True, blank=True)
    celular = models.CharField(max_length=20, null=True, blank=True)
    historia_clinica = models.TextField(null=True, blank=True)
    archivo = models.FileField(upload_to='pacientes/archivos/', null=True, blank=True)  # Asegúrate de que este campo esté aquí
    fecha_inicio = models.DateField(null=True, blank=True)
    ultima_consulta = models.DateField(null=True, blank=True)
    fecha_nacimiento = models.DateField(null=True, blank=True)
    discapacidad = models.BooleanField(default=False)
    discapacidad_detalle = models.CharField(max_length=250, null=True, blank=True)

    def calcular_edad(self):
        if self.fecha_nacimiento is None:
            return None  # O alguna otra lógica que quieras usar en caso de que no haya fecha de nacimiento
        today = date.today()
        return today.year - self.fecha_nacimiento.year - (
            (today.month, today.day) < (self.fecha_nacimiento.month, self.fecha_nacimiento.day)
        )
    
    def __str__(self) -> str:
        return f"{self.nombre} {self.apellido}"

    class Meta:
        verbose_name = "Paciente"
        verbose_name_plural = "Pacientes"

paciente/forms.py
from django import forms
from .models import Paciente

class PacienteForm(forms.ModelForm):
    class Meta:
        model = Paciente
        fields = [
            'nombre', 'apellido', 'email', 'celular', 'historia_clinica',
            'archivo', 'fecha_inicio', 'ultima_consulta', 'fecha_nacimiento',
            'discapacidad', 'discapacidad_detalle'
        ]
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'apellido': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'celular': forms.TextInput(attrs={'class': 'form-control'}),
            'historia_clinica': forms.Textarea(attrs={'class': 'form-control'}),
            'archivos': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'fecha_inicio': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'ultima_consulta': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'fecha_nacimiento': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'discapacidad_detalle': forms.Textarea(attrs={'class': 'form-control'}),
        }

paciente/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Paciente
from .forms import PacienteForm
from consultas.models import Consulta
from django.urls import reverse_lazy
from django.shortcuts import render, redirect

def home(request):
    pacientes = Paciente.objects.all()
    return render(request, 'paciente/editar_paciente.html', {'pacientes': pacientes})

def editar_paciente(request):
    return render(request, "paciente/editar_paciente.html")

class PacienteListView(ListView):
    model = Paciente
    template_name = 'paciente/paciente_list.html'
    context_object_name = 'pacientes'

class PacienteDetailView(DetailView):
    model = Paciente
    template_name = 'paciente/paciente_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['consultas'] = Consulta.objects.filter(paciente=self.object)
        context['adjuntos'] = self.object.adjuntos.all()
        return context

class PacienteCreateView(CreateView):
    model = Paciente
    form_class = PacienteForm
    template_name = 'paciente/paciente_form.html'
    success_url = reverse_lazy('paciente:paciente_list')

class PacienteUpdateView(UpdateView):
    model = Paciente
    form_class = PacienteForm
    template_name = 'paciente/paciente_form.html'
    success_url = reverse_lazy('paciente:paciente_list')

class PacienteDeleteView(DeleteView):
    model = Paciente
    template_name = 'paciente/paciente_confirm_delete.html'
    success_url = reverse_lazy('paciente:paciente_list')

paciente/templates/paciente/editar_paciente.html
{% extends 'core/base.html' %}

{% block titulo %}
    <h1 class="text-center mb-4">Gestionar Pacientes</h1>
{% endblock titulo %}

{% block contenido %}
<div class="container my-5">
    <h3 class="pb-3 border-bottom">Pacientes</h3>
    <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4">
        <a class="btn btn-primary me-md-2" href="{% url 'paciente:paciente_create' %}" role="button">Crear Paciente</a>
        <a class="btn btn-outline-primary" href="{% url 'paciente:paciente_list' %}" role="button">Listar Pacientes</a>
    </div>
    <div class="text-center mt-4">
        <a class="btn btn-secondary" href="{% url 'core:home' %}" role="button">Volver a Inicio</a>
    </div>
</div>
{% endblock contenido %}

paciente/templates/paciente/paciente_detail.html
{% extends 'core/base.html' %}

{% block titulo %}
    <h1 class="text-center mb-4">Detalle del Paciente</h1>
{% endblock titulo %}

{% block contenido %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h2>{{ object.nombre|title }} {{ object.apellido|title }}</h2>
            <p><strong>Email:</strong> {{ object.email }}</p>
            <p><strong>Celular:</strong> {{ object.celular }}</p>
            <p><strong>Fecha de nacimiento:</strong> {{ object.fecha_nacimiento|date:"d/m/Y" }}</p>
            <p><strong>Edad:</strong> {{ object.calcular_edad }}</p>
            <p><strong>Historia Clínica:</strong> {{ object.historia_clinica }}</p>

            <h3>Archivos Adjuntos</h3>
            <ul>
                {% for archivo in object.archivos.all %}
                    <li>
                        <a href="{{ adjunto.archivo.url }}" target="_blank">{{ adjunto.nombre }}</a>
                    </li>
                {% empty %}
                    <li>No hay archivos adjuntos.</li>
                {% endfor %}
            </ul>

            <h3 class="mt-4">Historial de Consultas</h3>
            <!-- DEJAMOS COMENTADO HASTA ARMAR LA PARTE DE CONSULTAS <ul>
                {% for consulta in consultas %}
                    <li>{{ consulta.fecha|date:"d/m/Y" }} - {{ consulta.motivo }}</li>
                {% empty %}
                    <li>No hay consultas registradas.</li>
                {% endfor %}
            </ul>
-->
            <div class="d-grid gap-2 d-md-flex justify-content-md-end mt-4">
                <a href="{% url 'paciente:paciente_update' object.id %}" class="btn btn-warning me-md-2">Editar Paciente</a>
                <a href="{% url 'paciente:paciente_delete' object.id %}" class="btn btn-danger me-md-2">Eliminar Paciente</a>
                <a href="{% url 'paciente:paciente_list' %}" class="btn btn-secondary">Volver a la lista</a>
            </div>
        </div>
    </div>
</div>
{% endblock contenido %}

paciente/templates/paciente/paciente_form.html
{% extends 'core/base.html' %}

{% block titulo %}
    <h1 class="text-center mb-4">{% if form.instance.pk %}Editar Paciente{% else %}Nuevo Paciente{% endif %}</h1>
{% endblock titulo %}

{% block contenido %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card shadow-sm border-light">
                <div class="card-body">
                    <h2 class="card-title text-center mb-4">
                        {% if form.instance.pk %}Editar Paciente{% else %}Nuevo Paciente{% endif %}
                    </h2>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }} <!-- Renderiza el formulario con estilos predefinidos -->
                        <div class="d-grid gap-2 d-md-flex justify-content-md-end mt-4">
                            <button type="submit" class="btn btn-primary">Guardar</button>
                            <a href="{% url 'paciente:paciente_list' %}" class="btn btn-secondary">Cancelar</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock contenido %}

paciente/templates/paciente/paciente_list.html
{% extends 'core/base.html' %}

{% block titulo %}
    <h1 class="text-center mb-4">Lista de Pacientes</h1>
{% endblock titulo %}

{% block contenido %}
<div class="container my-5">
    <div class="py-4">
        <form class="input-group mb-3"
              action="{% url 'paciente:paciente_list' %}"
              method="get">
            <input type="text"
                   class="form-control"
                   name="consulta"
                   placeholder="Buscar..."
                   aria-label="Buscar">
            <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Buscar</button>
        </form>
    </div>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Nombre</th>
                <th scope="col">Apellido</th>
                <th scope="col">Edad</th>
                <th scope="col">Última Consulta</th>
                <th scope="col">Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for paciente in object_list %}
                <tr>
                    <td>{{ paciente.nombre|title }}</td> <!-- Capitaliza el nombre -->
                    <td>{{ paciente.apellido|title }}</td> <!-- Capitaliza el apellido -->
                    <td>{{ paciente.calcular_edad }}</td> <!-- Usamos el método para calcular la edad -->
                    <td>{% if paciente.ultima_consulta %}{{ paciente.ultima_consulta|date:"d/m/Y" }}{% else %}No hay consultas{% endif %}</td> <!-- Mostramos la fecha de la última consulta -->
                    <td>
                        <a class="btn btn-info btn-sm me-1"
                           href="{% url 'paciente:paciente_detail' paciente.id %}">Detalle</a>
                        <a class="btn btn-warning btn-sm me-1"
                           href="{% url 'paciente:paciente_update' paciente.id %}">Cambiar</a>
                        <a class="btn btn-danger btn-sm"
                           href="{% url 'paciente:paciente_delete' paciente.id %}">Borrar</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="mt-4 text-center">
        <a class="btn btn-secondary"
           href="{% url 'core:paciente' %}"
           role="button">Volver a Pacientes</a>
    </div>
</div>
{% endblock contenido %}