config/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("usuario/", include("usuario.urls")),
    path("paciente/", include("paciente.urls")),
    path('turnos/', include('turnos.urls')),
]

core/urls.py
from django.contrib.auth.views import LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from . import views

app_name = "core"


urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(template_name="core/logout.html"), name="logout"),
    path("register/", views.register, name="register"),
    path("about/", views.about, name="about"),
    path("paciente/", views.paciente, name="paciente"),
    path("turnos/", views.turnos, name="turnos"),
    
]

urlpatterns += staticfiles_urlpatterns()

paciente/urls.py
from django.urls import path
from . import views

app_name = "paciente"

urlpatterns = [
    path("", views.home, name="home"),
    path("editar_paciente/", views.editar_paciente, name="editar_paciente"),
    path("paciente/list/", views.PacienteListView.as_view(), name="paciente_list"),
    path("paciente/create/", views.PacienteCreateView.as_view(), name="paciente_create"),
    path("paciente/detail/<int:pk>", views.PacienteDetailView.as_view(), name="paciente_detail"),
    path("paciente/update/<int:pk>", views.PacienteUpdateView.as_view(), name="paciente_update"),
    path("paciente/delete/<int:pk>", views.PacienteDeleteView.as_view(), name="paciente_delete"),
]

turnos/urls.py
from django.urls import path
from . import views

app_name = 'turnos'


urlpatterns = [
    path('turnos/', views.turnos, name='turnos'),
    path('turnos/lista/', views.listar_turnos, name='listar_turnos'), 
    path('turnos/nuevo/', views.crear_turno, name='crear_turno'),
    path('<int:id>/', views.detalle_turno, name='detalle_turno'),
    path('<int:id>/editar/', views.editar_turno, name='editar_turno'),
    path('<int:id>/eliminar/', views.eliminar_turno, name='eliminar_turno'),
]

core/models.py
from django.db import models

# Create your models here.

paciente/models.py
from django.db import models
from django.utils import timezone
from datetime import date

class Paciente(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    email = models.EmailField(max_length=254, null=True, blank=True)
    celular = models.CharField(max_length=20, null=True, blank=True)
    historia_clinica = models.TextField(null=True, blank=True)
    archivo = models.FileField(upload_to='pacientes/archivos/', null=True, blank=True)  # Asegúrate de que este campo esté aquí
    fecha_inicio = models.DateField(null=True, blank=True)
    ultima_consulta = models.DateField(null=True, blank=True)
    fecha_nacimiento = models.DateField(null=True, blank=True)
    discapacidad = models.BooleanField(default=False)
    discapacidad_detalle = models.CharField(max_length=250, null=True, blank=True)

    def calcular_edad(self):
        if self.fecha_nacimiento is None:
            return None  # O alguna otra lógica que quieras usar en caso de que no haya fecha de nacimiento
        today = date.today()
        return today.year - self.fecha_nacimiento.year - (
            (today.month, today.day) < (self.fecha_nacimiento.month, self.fecha_nacimiento.day)
        )
    
    def __str__(self) -> str:
        return f"{self.nombre} {self.apellido}"

    class Meta:
        verbose_name = "Paciente"
        verbose_name_plural = "Pacientes"

core/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ["username", "password"]
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "password": forms.PasswordInput(attrs={"class": "form-control"}),
        }


class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, widget=forms.TextInput(attrs={"class": "form-control"}))
    last_name = forms.CharField(max_length=30, required=True, widget=forms.TextInput(attrs={"class": "form-control"}))
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={"class": "form-control"}))
    birth_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"class": "form-control", "type": "date"}))

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email", "birth_date", "password1", "password2"]
        help_texts = {k: "" for k in fields}
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "password1": forms.PasswordInput(attrs={"class": "form-control"}),
            "password2": forms.PasswordInput(attrs={"class": "form-control"}),
        }

paciente/forms.py
from django import forms
from .models import Paciente

class PacienteForm(forms.ModelForm):
    class Meta:
        model = Paciente
        fields = [
            'nombre', 'apellido', 'email', 'celular', 'historia_clinica',
            'archivo', 'fecha_inicio', 'ultima_consulta', 'fecha_nacimiento',
            'discapacidad', 'discapacidad_detalle'
        ]
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'apellido': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'celular': forms.TextInput(attrs={'class': 'form-control'}),
            'historia_clinica': forms.Textarea(attrs={'class': 'form-control'}),
            'archivos': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'fecha_inicio': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'ultima_consulta': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'fecha_nacimiento': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'discapacidad_detalle': forms.Textarea(attrs={'class': 'form-control'}),
        }

core/views.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.views import LoginView
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect

from .forms import CustomAuthenticationForm, CustomUserCreationForm

def home(request):
    return render(request, "core/index.html")

def turnos(request):
    return render(request, "turnos/turnos.html")

def about(request):
    return render(request, "core/about.html")

def paciente(request):
    return render(request, "core/paciente.html")

def editar_producto(request):
    return render(request, "paciente/index.html")

class CustomLoginView(LoginView):
    authentication_form = CustomAuthenticationForm
    template_name = "core/login.html"

def register(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)  # Autenticar al usuario después de registrarse
            messages.success(request, 'Cuenta creada exitosamente.')
            return redirect('core:home')
        else:
            messages.error(request, 'Por favor corrige los errores a continuación.')
    else:
        form = CustomUserCreationForm()
    return render(request, "core/register.html", {"form": form})

paciente/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Paciente
from .forms import PacienteForm
from consultas.models import Consulta
from django.urls import reverse_lazy
from django.shortcuts import render, redirect

def home(request):
    pacientes = Paciente.objects.all()
    return render(request, 'paciente/editar_paciente.html', {'pacientes': pacientes})

def editar_paciente(request):
    return render(request, "paciente/editar_paciente.html")

class PacienteListView(ListView):
    model = Paciente
    template_name = 'paciente/paciente_list.html'
    context_object_name = 'pacientes'

class PacienteDetailView(DetailView):
    model = Paciente
    template_name = 'paciente/paciente_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['consultas'] = Consulta.objects.filter(paciente=self.object)
        context['adjuntos'] = self.object.adjuntos.all()
        return context

class PacienteCreateView(CreateView):
    model = Paciente
    form_class = PacienteForm
    template_name = 'paciente/paciente_form.html'
    success_url = reverse_lazy('paciente:paciente_list')

class PacienteUpdateView(UpdateView):
    model = Paciente
    form_class = PacienteForm
    template_name = 'paciente/paciente_form.html'
    success_url = reverse_lazy('paciente:paciente_list')

class PacienteDeleteView(DeleteView):
    model = Paciente
    template_name = 'paciente/paciente_confirm_delete.html'
    success_url = reverse_lazy('paciente:paciente_list')

core/templates/core/about.html
{% extends 'core/base.html' %}
{% load static %}
{% block titulo %}
<div class="row gx-4 gx-lg-5 align-items-center">
    <div class="col-lg-12 text-center">
        <h1 class="font-weight-light text-white">Nosotros</h1>
    </div>
</div>
{% endblock titulo %}
{% block contenido %}


    <!-- Heading Row-->
    <div class="row gx-4 gx-lg-5 align-items-center my-5">
        <div class="col-lg-7">
            <img class="nosotros img-fluid rounded mb-4 mb-lg-0"
                 src="{% static 'core/img/nosotros.png' %}"
                 alt="..." />
        </div>
        <div class="col-lg-5">
            
            <p>
                Un desarrollador novato que, inspirado por una gran idea (y necesidad) de su hermano, se animó a crear esta aplicación. Nuestro objetivo es facilitar la gestión de turnos y permitir al personal de salud tener una historia clínica y una base de datos centralizada.

Con esta herramienta, esperamos que en el futuro se pueda coordinar el tratamiento de pacientes de manera conjunta, mejorando así la eficiencia y la calidad del cuidado médico. Siempre buscando ser nuestra mejor versión estamos abiertos a consultas o ideas que crean que puedan mejorar la experiencia del usuario.
            </p>
            <div>
                <a class="btn btn-secondary" href="{% url 'core:home' %}" role="button">Volver a Inicio</a>
            </div>
        </div>
    </div>


{% endblock contenido %}

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>{% block title %}MedicalAssistent{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'core/assets/favicon.ico' %}" />
    <link href="{% static 'core/css/styles.css' %}" rel="stylesheet" />
    <link href="{% static 'core/css/titulo_styles.css' %}" rel="stylesheet" />
    <link href="{% static 'core/css/usuarios_styles.css' %}" rel="stylesheet" />
    <link href="{% static 'core/css/producto_styles.css' %}" rel="stylesheet" />
    <link href="{% static 'core/css/login_styles.css' %}" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/css/lightbox.min.css" rel="stylesheet">
    <link href="{% static 'core/css/turnos_styles.css' %}" rel="stylesheet" />
    
</head>
<body>
    {% include 'core/components/navbar.html' %}
    <div class="container px-4 px-lg-5">
        {% if messages %}
            <div>
                {% for message in messages %}
                    <div class="alert {% if message.tags %}alert-{{ message.tags }}{% else %}alert-info{% endif %}">
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        {% endif %}
        {% block contenido %}{% endblock %}
    </div>
    {% include 'core/components/footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'core/js/scripts.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/js/lightbox.min.js"></script>
    {% block extra_js %}
        <script src="{% static 'turnos/js/turnos_custom.js' %}"></script>
    {% endblock %}
</body>
</html>

core/templates/core/index.html
<!-- index.html -->
{% extends 'core/base.html' %}
{% load static %}
{% block titulo %}
    Inicio
{% endblock titulo %}
{% block contenido %}
    <div class="row gx-4 gx-lg-5 align-items-center my-5">
        <div class="col-lg-7">
            <img class="img-fluid rounded mb-4 mb-lg-0" src="{% static 'core/img/index.png' %}" alt="MedicalAssistent" />
        </div>
        <div class="col-lg-5">
            <h1 class="font-weight-light d-flex justify-content-between">
                Medical Assistent
                {% if not user.is_authenticated %}
                    <a href="{% url 'core:login' %}" class="btn btn-secondary align-self-center">Iniciar Sesión</a>
                {% endif %}
            </h1>
            <p>
                Es una aplicación diseñada exclusivamente para optimizar el trabajo del personal de la salud. Inicialmente pensada para Kinesiólogos y Quiroprácticos, pero con posibilidades de uso para otras disciplinas como la medicina, psicología o psicopedagogía entre otros. MedicalAssistent será tu asistente personal en tu computadora o celular, que facilitará la gestión de turnos, y donde también podrás organizar la historia clínica de los pacientes, acceder a material bibliográfico, y muchas cosas más de manera fácil, rápida y eficiente.
            </p>
            <p>
                Por cualquier problema, o sugerencia para mejorar la experiencia de usuario, siéntete libre de mandarnos un mensaje<br> 
                <a class="btn btn-primary" href="https://wa.me/5492213993941" target="_blank">WhatsApp</a>
            </p>
        </div>
    </div>

    {% if user.is_authenticated %}
        <p class="fs-2">Bienvenido {{ user.username }}</p>
        <!-- Mostrar contenido solo si el usuario está autenticado -->
        <!-- Call to Action-->
        <div class="card text-white bg-secondary my-5 py-4 text-center">
            <div class="card-body">
                <p class="productos">Accesos útiles</p>
            </div>
        </div>
        <!-- Content Row-->
        <div class="row gx-4 gx-lg-5">
            {% include 'core/components/card.html' with titulo="Lista de pacientes" texto="Hacé click aquí para ver el listado de pacientes." %}
            {% include 'core/components/card2.html' with titulo="Crear paciente" texto="Hacé click para crear un nuevo paciente." %}
            {% include 'core/components/card3.html' with titulo="Lista de turnos" texto="Hacé click aquí para ver los turnos en el calendario." %}
            {% include 'core/components/card4.html' with titulo="Crear turno" texto="Hacé click aquí para crear un turno nuevo" %}
        </div>
    {% endif %}
{% endblock contenido %}

core/templates/core/login.html
{% extends 'core/base.html' %}


{% block contenido %}
    <div class="login-container">
        <h1>Login</h1>
        <form method="post">
            {% csrf_token %}
            <label for="id_username">Usuario</label>
            {{ form.username }}
            <label for="id_password">Contraseña</label>
            {{ form.password }}
            <input type="hidden" name="next" value="{% url 'core:home' %}">
            <button type="submit" class="btn btn-primary">Iniciar Sesión</button>
            <a href="{% url 'core:home' %}" class="btn btn-secondary">Cancelar</a>
        </form>
        <hr>
        <div class="social-buttons">
            <a href="#" class="btn btn-google">Login con Google</a>
            <a href="#" class="btn btn-facebook">Login con Facebook</a>
        </div>
        <div class="register-message">
            <p>¿No tienes una cuenta?</p>
            <a href="{% url 'core:register' %}" class="btn btn-success">Regístrate</a>
        </div>
    </div>
{% endblock contenido %}

core/templates/core/logout.html
{% extends 'core/base.html' %}
{% block titulo %}
    <h1 class="logout">Logout</h1>
{% endblock titulo %}
{% block contenido %}
    <h1 class="display-4">Se cerró la sesión. Hasta la próxima!!</h1>
    <a class="btn btn-secondary" href="{% url 'core:home' %}" role="button">Volver a Inicio</a>
{% endblock contenido %}

core/templates/core/paciente.html
{% extends 'core/base.html' %}
{% load static %}
{% block titulo %}
<div class="row gx-4 gx-lg-5 align-items-center">
    <div class="col-lg-12 text-center">
        <h1 class="font-weight-light text-white">Pacientes</h1>
    </div>
</div>
{% endblock titulo %}
{% block contenido %}

<!-- Pacientes -->

<!-- Imagen Principal y Tarjetas -->
<section class="mb-5 mt-4">
    <div class="container">
        <div class="row gx-4 gx-lg-5 align-items-start">
            <div class="col-lg-6 mb-4">
                <img class="img-fluid" src="{% static 'core/img/pacientes.png' %}" alt="Pacientes" />
            </div>
            <div class="col-lg-6">
                <div class="row gx-4 gx-lg-5 align-items-stretch">
                    <div class="col-md-6 mb-4">
                        <div class="card card-custom h-100">
                            <div class="card-body">
                                <h2 class="card-title">Lista de pacientes</h2>
                                <p class="card-text">Hacé click aquí para ver el listado de pacientes.</p>
                            </div>
                            <div class="card-footer">
                                <a class="btn btn-secondary btn-sm" href="{% url 'paciente:paciente_list' %}">Ver</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 mb-4">
                        <div class="card card-custom h-100">
                            <div class="card-body">
                                <h2 class="card-title">Crear paciente</h2>
                                <p class="card-text">Hacé click para crear un nuevo paciente.</p>
                            </div>
                            <div class="card-footer">
                                <a class="btn btn-secondary btn-sm" href="{% url 'paciente:paciente_create' %}">Crear</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 mb-4">
                        <div class="card card-custom h-100">
                            <div class="card-body">
                                <h2 class="card-title">Lista de turnos</h2>
                                <p class="card-text">Hacé click aquí para ver los turnos en el calendario.</p>
                            </div>
                            <div class="card-footer">
                                <a class="btn btn-secondary btn-sm" href="{% url 'turnos:listar_turnos' %}">Ver</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 mb-4">
                        <div class="card card-custom h-100">
                            <div class="card-body">
                                <h2 class="card-title">Crear turno</h2>
                                <p class="card-text">Hacé click aquí para crear un turno nuevo.</p>
                            </div>
                            <div class="card-footer">
                                <a class="btn btn-secondary btn-sm" href="{% url 'turnos:crear_turno' %}">Crear</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Botón Volver a Inicio -->
<section class="mb-5 text-center">
    <div class="container">
        <a class="btn btn-secondary" href="{% url 'core:home' %}" role="button">Volver a Inicio</a>
    </div>
</section>

{% endblock contenido %}

core/templates/core/register.html
{% extends 'core/base.html' %}

{% block titulo %}
    <h1 class="registro">Registro de usuario</h1>
{% endblock titulo %}

{% block contenido %}

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Registrar nuevo usuario</button> <a href="{% url 'core:home' %}" class="btn btn-secondary">Cancelar</a>
    </form>
    

{% endblock contenido %}