config/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("usuario/", include("usuario.urls")),
    path("paciente/", include("paciente.urls")),
    path('turnos/', include('turnos.urls')),
]

core/urls.py
from django.contrib.auth.views import LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from . import views

app_name = "core"


urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(template_name="core/logout.html"), name="logout"),
    path("register/", views.register, name="register"),
    path("about/", views.about, name="about"),
    path("paciente/", views.paciente, name="paciente"),
    path("turnos/", views.turnos, name="turnos"),
    
]

urlpatterns += staticfiles_urlpatterns()

paciente/urls.py
from django.urls import path
from . import views

app_name = "paciente"

urlpatterns = [
    path("", views.home, name="home"),
    path("editar_paciente/", views.editar_paciente, name="editar_paciente"),
    path("paciente/list/", views.PacienteListView.as_view(), name="paciente_list"),
    path("paciente/create/", views.PacienteCreateView.as_view(), name="paciente_create"),
    path("paciente/detail/<int:pk>", views.PacienteDetailView.as_view(), name="paciente_detail"),
    path("paciente/update/<int:pk>", views.PacienteUpdateView.as_view(), name="paciente_update"),
    path("paciente/delete/<int:pk>", views.PacienteDeleteView.as_view(), name="paciente_delete"),
]

turnos/urls.py
from django.urls import path
from . import views

app_name = 'turnos'


urlpatterns = [
    path('turnos/', views.turnos, name='turnos'),
    path('turnos/lista/', views.listar_turnos, name='listar_turnos'), 
    path('turnos/nuevo/', views.crear_turno, name='crear_turno'),
    path('<int:id>/', views.detalle_turno, name='detalle_turno'),
    path('<int:id>/editar/', views.editar_turno, name='editar_turno'),
    path('<int:id>/eliminar/', views.eliminar_turno, name='eliminar_turno'),
]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ["username", "password"]
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "password": forms.PasswordInput(attrs={"class": "form-control"}),
        }


class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, widget=forms.TextInput(attrs={"class": "form-control"}))
    last_name = forms.CharField(max_length=30, required=True, widget=forms.TextInput(attrs={"class": "form-control"}))
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={"class": "form-control"}))
    birth_date = forms.DateField(required=True, widget=forms.DateInput(attrs={"class": "form-control", "type": "date"}))

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email", "birth_date", "password1", "password2"]
        help_texts = {k: "" for k in fields}
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "password1": forms.PasswordInput(attrs={"class": "form-control"}),
            "password2": forms.PasswordInput(attrs={"class": "form-control"}),
        }

core/views.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.views import LoginView
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect

from .forms import CustomAuthenticationForm, CustomUserCreationForm

def home(request):
    return render(request, "core/index.html")

def turnos(request):
    return render(request, "turnos/turnos.html")

def about(request):
    return render(request, "core/about.html")

def paciente(request):
    return render(request, "core/paciente.html")

def editar_producto(request):
    return render(request, "paciente/index.html")

class CustomLoginView(LoginView):
    authentication_form = CustomAuthenticationForm
    template_name = "core/login.html"

def register(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)  # Autenticar al usuario después de registrarse
            messages.success(request, 'Cuenta creada exitosamente.')
            return redirect('core:home')
        else:
            messages.error(request, 'Por favor corrige los errores a continuación.')
    else:
        form = CustomUserCreationForm()
    return render(request, "core/register.html", {"form": form})

core/templates/core/components/card.html
<div class="col-md-4 mb-5">
    <div class="card h-90">
        <div class="card-body">
            <h2 class="card-title">{{ titulo }}</h2>
            <p class="card-text">{{ texto }}</p>
        </div>
        <div class="card-footer">
            <a class="btn btn-secondary btn-sm" href="{% url 'paciente:paciente_list' %}">Ver más</a>
        </div>
    </div>
</div>

core/templates/core/components/card2.html
<div class="col-md-4 mb-5">
    <div class="card h-90">
        <div class="card-body">
            <h2 class="card-title">{{ titulo }}</h2>
            <p class="card-text">{{ texto }}</p>
        </div>
        <div class="card-footer">
            <a class="btn btn-secondary btn-sm" href="{% url 'paciente:paciente_create' %}">Ver más</a>
        </div>
    </div>
</div>

core/templates/core/components/card3.html
<div class="col-md-4 mb-5">
    <div class="card h-90">
        <div class="card-body">
            <h2 class="card-title">{{ titulo }}</h2>
            <p class="card-text">{{ texto }}</p>
        </div>
        <div class="card-footer">
            <a class="btn btn-secondary btn-sm" href="{% url 'turnos:turnos' %}">Ver más</a>
        </div>
    </div>
</div>

core/templates/core/components/card4.html
<div class="col-md-4 mb-5">
    <div class="card h-90">
        <div class="card-body">
            <h2 class="card-title">{{ titulo }}</h2>
            <p class="card-text">{{ texto }}</p>
        </div>
        <div class="card-footer">
            <a class="btn btn-secondary btn-sm" href="{% url 'turnos:crear_turno' %}">Ver más</a>
        </div>
    </div>
</div>

core/templates/core/components/footer.html
<footer class="py-2 bg-dark fixed-bottom">
    <div class="container px-4 px-lg-5">
        <p class="m-0 text-center text-white">Medical Assistent © was developed by Alejo Pardini</p>
    </div>
</footer>

core/templates/core/components/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="{% url 'core:home' %}">Medical Assistent</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link {% if request.path == '/' %} active {% endif %}" href="{% url 'core:home' %}">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == '/about/' %} active {% endif %}" href="{% url 'core:about' %}">Nosotros</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == '/pacientes/' %} active {% endif %}" href="{% url 'core:paciente' %}">Pacientes</a>
                    </li>
                    {% if user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == '/turnos/' %} active {% endif %}" href="{% url 'turnos:turnos' %}">Turnos</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link text-bg-info">{{ user.username }}</a>
                    </li>
                    <li class="nav-item">
                        <form action="{% url 'core:logout' %}" method="post" class="d-inline">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-dark">Logout</button>
                        </form>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == '/login/' %} active {% endif %}" href="{% url 'core:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == '/register/' %} active {% endif %}" href="{% url 'core:register' %}">Registrarse</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>